In [1]:
# import libraries
import cv2


## test of normalizing an image (preprocessing)

In [2]:
# test on normalizing the image
img_before_norm = cv2.imread('./drowsiness-dataset/train/Open_Eyes/s0001_02334_0_0_1_0_0_01.png')
print(img_before_norm)

[[[38 38 38]
  [40 40 40]
  [44 44 44]
  ...
  [89 89 89]
  [91 91 91]
  [90 90 90]]

 [[36 36 36]
  [40 40 40]
  [45 45 45]
  ...
  [92 92 92]
  [89 89 89]
  [90 90 90]]

 [[36 36 36]
  [41 41 41]
  [44 44 44]
  ...
  [91 91 91]
  [91 91 91]
  [90 90 90]]

 ...

 [[48 48 48]
  [49 49 49]
  [53 53 53]
  ...
  [71 71 71]
  [71 71 71]
  [74 74 74]]

 [[49 49 49]
  [49 49 49]
  [53 53 53]
  ...
  [69 69 69]
  [71 71 71]
  [72 72 72]]

 [[48 48 48]
  [51 51 51]
  [51 51 51]
  ...
  [71 71 71]
  [69 69 69]
  [71 71 71]]]


In [3]:
# normalizing image
img_normalized = cv2.normalize(img_before_norm, None, 0, 1, cv2.NORM_MINMAX, cv2.CV_32F)
print(type(img_normalized))

<class 'numpy.ndarray'>


 ## loop through images and normalize them all

In [4]:
import os
# how do i go through and normalize all the images in the dataset?
